# Generated by Django 4.2 on 2024-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('in_progress', 'Принято в работу')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
