# Generated by Django 4.2 on 2024-11-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_application_category_delete_designrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('work', 'Принято в работу'), ('done', 'Выполнено')], default='new', max_length=10),
        ),
    ]
